from django.conf.urls import url, include
from core.views import (
    home, 
    lista_pessoas, 
    nova_pessoa,
    pessoa_update,
    pessoa_delete,
    lista_veiculos,
    novo_veiculo,
    veiculo_update,
    veiculo_delete,
    lista_mov_rot, 
    novo_mov_rot,
    mov_rot_update,
    mov_rot_delete,
    lista_mensalista,
    novo_mensalista,
    mensalista_update,
    mensalista_delete,
    lista_mov_mens,
    mov_mensalista_novo,
    mov_mensalista_update,
    mov_mensalista_delete
)


urlpatterns = [
    url(r'^mov-mensalista-delete/(?P<id>\d+)/$', mov_mensalista_delete, name='core_mov_mensalista_delete'),
    url(r'^mov-mensalista-update/(?P<id>\d+)/$', mov_mensalista_update, name='core_mov_mensalista_update'),
    url('mov-mensalista-novo', mov_mensalista_novo, name='core_mov_mensalista_novo'),
    url('mov_mens', lista_mov_mens, name='core_lista_mov_mens'),
    url(r'^mensalista-delete/(?P<id>\d+)/$', mensalista_delete, name='core_mensalista_delete'), 
    url(r'^mensalista-update/(?P<id>\d+)/$', mensalista_update, name='core_mensalista_update'), 
    url('novo-mensalista', novo_mensalista, name='core_novo_mensalista'),
    url('mensalista', lista_mensalista, name='core_lista_mensalista'),
    url(r'^mov-rot-delete/(?P<id>\d+)/$', mov_rot_delete, name='core_mov_rot_delete'), 
    url(r'^mov-rot-update/(?P<id>\d+)/$', mov_rot_update, name='core_mov_rot_update'), 
    url('mov_rot', lista_mov_rot, name='core_lista_mov_rot'),  
    url('novo_mov_rot', novo_mov_rot, name='core_novo_mov_rot'),
    url(r'^veiculo-delete/(?P<id>\d+)/$', veiculo_delete, name='core_veiculo_delete'),
    url(r'^veiculo-update/(?P<id>\d+)/$', veiculo_update, name='core_veiculo_update'), 
    url('veiculos', lista_veiculos, name='core_lista_veiculos'),
    url('novo-veiculo', novo_veiculo, name='core_novo_veiculo'),  
    url(r'^pessoa-delete/(?P<id>\d+)/$', pessoa_delete, name='core_pessoa_delete'),
    url(r'^pessoa-update/(?P<id>\d+)/$', pessoa_update, name='core_pessoa_update'),
    url('pessoas', lista_pessoas, name='core_lista_pessoas'),
    url('nova-pessoa', nova_pessoa, name='core_nova_pessoa'),
    url('', home, name='core_home'),
]
